changelog:
  categories:
    - title: New Features
      labels:
        - type/feature
    - title: Bug Fixes
      labels:
        - type/bug
    - title: UX Improvements
      labels:
        - type/user-experience
    - title: Maintenance
      labels:
        - type/chore
        - type/refactor
    - title: Other Changes
      labels:
        - "*"
