name: Bug Report
description: Report something that's broken
labels: ["type/bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear description of the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened instead?
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Frontend (UI)
        - Backend (API)
        - Ingestion (articles)
        - Infrastructure (CI/CD, deployment)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Logs, screenshots, steps to reproduce
    validations:
      required: false
