name: Feature Request
description: Suggest a new feature or improvement
labels: ["type/feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: What should be built?
      description: Clear description of the feature
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this valuable?
      description: What problem does this solve or what opportunity does it create?
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Frontend (UI)
        - Backend (API)
        - Ingestion (articles)
        - Infrastructure (CI/CD, deployment)
        - Content / UX
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How do we know this is done?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: false
